server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    #register-with-eureka: false和fetch-registry: false表示自己是一个eureka server
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defualt-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eureka-server
