server:
  port: 8899
spring:
  application:
    name: spring-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    feign:
      path: /feign/**
      serviceId: spring-feign
