server:
  port: 9004
spring:
  application:
    name: spring-feign
  zipkin:
    base-url: http://localhost:9411/
    sleuth:
      sampler:
        probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health, info, hystrix.stream