server:
  port: 9001
spring:
  application:
    name: service-hello
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    service-url:
      defualtZone: http://localhost:8761/eureka/
